KAFKA_BROKER = 'kafka:9092'
KAFKA_TOPIC_FLIGHT = 'ft_flight'
KAFKA_TOPIC_PASSENGER = 'ft_passenger'
KAFKA_TOPIC_BOOKING = 'ft_booking'
KAFKA_TOPIC_BAGGAGE = 'ft_baggage'
KAFKA_TOPIC_CREW_ASSIGNMENT = 'ft_crew_assignment'
KAFKA_TOPIC_PASSENGER_NOTIFICATION = 'ft_passenger_notification'
KAFKA_TOPIC_FLIGHT_INCIDENT = 'ft_flight_incident'
KAFKA_TOPIC_PASSENGER_FEEDBACK = 'ft_passenger_feedback'
KAFKA_TOPIC_FLIGHT_FUEL = 'ft_flight_fuel'
KAFKA_TOPIC_MAINTENANCE_EVENT = 'ft_maintenance_event'

BATCH_SIZE_FLIGHT = 100
BATCH_SIZE_PASSENGER = 500
BATCH_SIZE_BOOKING = 300
BATCH_SIZE_BAGGAGE = 300
BATCH_SIZE_CREW_ASSIGNMENT = 100
BATCH_SIZE_PASSENGER_NOTIFICATION = 200
BATCH_SIZE_FLIGHT_INCIDENT = 30
BATCH_SIZE_PASSENGER_FEEDBACK = 100
BATCH_SIZE_FLIGHT_FUEL = 50
BATCH_SIZE_MAINTENANCE_EVENT = 20

PRODUCE_INTERVAL_SECONDS = 300  # 5 dakika 